### ISSUE TITLE
Simpler way ?

### ISSUE THREAD

**Issue by lpatiny** [jobo322/linearSumAssignment#18]
Could we have another method that calculates this internally ? 

```js
const diff = xValueExperimental.map((experimental) => {
  return xValuePredicted.map((predicted) => {
    return Math.abs(predicted - experimental);
  });
});
```

I don't know about a correct name but it would be something like:

abcd(experimental, predicted, {})

And one of the options could be a callback like
`distance: (a,b) => Math.abs(a-b)`

**Comment by jobo322** [comment]
There is a PR on [ml-spectra-processing](https://github.com/mljs/spectra-processing/pull/151) adding the function `xCostMatrix` with it is possible to generate a cost matrix, it accepts a function as an option to generate the cost matrix as you want.

So with this we will have 
```js
import { xcostMatrix } from 'ml-spectra-processing';

const diff = xCostMatrix(experimental, predicted, { 
   fct: (a, b) => Math.abs(a - b)
});
```

by default the function used by `xCostMatrix` is the absolute value of the difference
